# Generated by Django 5.1.4 on 2026-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_review_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
