# Generated by Django 5.1.4 on 2026-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_category_en_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Обробляється'), ('Shipped', 'Відправлено'), ('Delivered', 'Доставлено'), ('Returned', 'Повернено'), ('Lost', 'Втрачено')], default='Processing', max_length=20),
        ),
    ]
